### ISSUE TITLE
Quick Fix: "represents" typo and Change to "it's"

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/html-tables-lab#1]
Quick Fixes
1. Typo for "represents" 
**************************
Introduce the Table Data Tag: <td>
In the second row, we can start putting in our data. Here, we want to use the table data tag, <td> instead of using the table header tag. The <td> tag representes one table cell. So, for our party table, we can add in some names, phone numbers and items for guests to bring. An example row would look like the following:

2. Line 2: Change "its" to "it's" (contraction)
**********************************
Reinforce Our Understanding Of HTML Tables Through Creation
Okay, now its time to put what we've learned to the test. For this challenge, your task is to recreate a table using the following data:

**Comment by rrcobb** [comment]
Thanks for reporting, fixed!

For the future - when you include a line number, it's helpful for it to be the line number within the overall file, not just the section. Most text editors support showing the line number next to each line. If your editor doesn't, you can click the pencil icon in github and see the line numbers there. Thanks again!
